// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeCypher(arg1:string):Promise<void>;

export function ChangeParams(arg1:number):Promise<void>;

export function Cypher(arg1:string):Promise<string>;

export function Decypher(arg1:string):Promise<string>;
