// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeCypher(arg1) {
  return window['go']['app']['App']['ChangeCypher'](arg1);
}

export function ChangeParams(arg1) {
  return window['go']['app']['App']['ChangeParams'](arg1);
}

export function Cypher(arg1) {
  return window['go']['app']['App']['Cypher'](arg1);
}

export function Decypher(arg1) {
  return window['go']['app']['App']['Decypher'](arg1);
}
